// <auto-generated />
namespace ProduceExchange.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatetocategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetocategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201605010144419_update to category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
